### PR TITLE
pass in app,passport to routes/users

### PR DESCRIPTION
**Pull request by dmcguinness**

### CODE REVIEW

**Comment by SamTay** [comment]
Ok. Another question. I've never actually used Github for collaboration -
my company has its own internal tools plus like beanstalk and stuff. Are
you sending me these requests because you want me to review and then hit
merge to master? So that we can both agree on what goes into master?

Samuel Tay
(631) 291-3866
sam.chong.tay@gmail.com

**Comment by SamTay** [comment]
Either way, code looks good to me. Although shit, I should have been able to figure that out.

**Comment by SamTay** [comment]
I really wanna hit this big green button, but I like specifying --no-ff for merging to a master branch. I'm gonna go ahead and do that - hopefully it is smart enough to close out the pull request afterwards.

**Comment by dmcguinness** [comment]
Yep! Typical workflow is that I never merge my own branches and you never merge your own branches (unless given a go ahead from the other collaborator). That way we both see what's going in and can sigh off on it.

**Pull request merged**
