### PR TITLE
Feature/send conf email

### PR DESCRIPTION
**Pull request by dmcguinness**

### CODE REVIEW

**Comment by dmcguinness** [comment]
@SamTay

**Comment by dmcguinness** [comment]
I'm going to merge, but take a look to see what's up with it.

**Comment by SamTay** [comment]
All makes sense to me - this is exactly what you asked me to do right? Haha. I'm still messing around with Mongoose but if you wana send me another request feel free.

**Comment by dmcguinness** [comment]
Ah yeah haha I was thinking the messaging system (i.e. create `Thread` and `Message` db schemas) might be the best thing to do. This is just for sending a confirmation email, but also includes a little refactor of my inline routes too hah

**Pull request merged**
